#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

printf "\n"
echo "--------- Running commitlint to validate commit message  ---------"
printf "\n"

npx --no-install commitlint --edit $1

printf "\n"
